name: Fork testing
on:
  push:
  pull_request:
    types:
      - opened

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: echo secret
        run:  var=${{ secrets.PASSWORD }}; echo $var
      - name: echo var
        run: echo ${{ vars.USERNAME }}